"""Initial migration

Revision ID: 7115af7ba495
Revises: b7d73ef92b25
Create Date: 2024-09-05 14:40:57.865856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7115af7ba495'
down_revision = 'b7d73ef92b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('calculatefeatures')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculatefeatures', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
