"""add some final datas

Revision ID: 753bd036de6e
Revises: 8ddfb14860a7
Create Date: 2024-09-11 14:11:00.222557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753bd036de6e'
down_revision = '8ddfb14860a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_matrices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('final_confusion_matrices', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('final_confusion_matrices')
        batch_op.drop_column('final_matrices')

    # ### end Alembic commands ###
