"""add some extra file feilds

Revision ID: b5bca021e0e5
Revises: 7115af7ba495
Create Date: 2024-09-05 20:45:05.343562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bca021e0e5'
down_revision = '7115af7ba495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_model')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scalerfile', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('encodingfile', sa.String(length=255), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('encodingfile')
        batch_op.drop_column('scalerfile')

    op.create_table('_alembic_tmp_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('about_dataset', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('heatmap_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('algorithm_used', sa.TEXT(), nullable=False),
    sa.Column('best_algorithm', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model_type', sa.TEXT(), nullable=False),
    sa.Column('source_link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('scalerfile', sa.VARCHAR(length=255), nullable=False),
    sa.Column('encodingfile', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
