"""Initial migration

Revision ID: b7d73ef92b25
Revises: 
Create Date: 2024-09-05 13:49:23.082994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d73ef92b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('datatype', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('about_dataset', sa.Text(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('heatmap_image', sa.String(length=200), nullable=True),
    sa.Column('algorithm_used', sa.Text(), nullable=False),
    sa.Column('best_algorithm', sa.String(length=100), nullable=True),
    sa.Column('calculatefeatures', sa.Text(), nullable=False),
    sa.Column('model_type', sa.Text(), nullable=False),
    sa.Column('source_link', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    op.drop_table('friend')
    op.drop_table('feature')
    # ### end Alembic commands ###
