"""cnn created

Revision ID: d8bf29f80209
Revises: f718a8b9c01d
Create Date: 2024-09-24 10:52:48.717539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bf29f80209'
down_revision = 'f718a8b9c01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ann',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('scalerfile', sa.String(length=255), nullable=True),
    sa.Column('objectives', sa.String(length=255), nullable=True),
    sa.Column('cross_validation', sa.Float(precision=3), nullable=True),
    sa.Column('data_cleaning', sa.Text(), nullable=True),
    sa.Column('hyperparameter', sa.Text(), nullable=True),
    sa.Column('feature_creation', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('matrices', sa.Text(), nullable=True),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('confusion_matrices', sa.Text(), nullable=True),
    sa.Column('final_matrices', sa.Text(), nullable=True),
    sa.Column('final_confusion_matrices', sa.Text(), nullable=True),
    sa.Column('encodingfile', sa.String(length=255), nullable=True),
    sa.Column('about_dataset', sa.Text(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('heatmap_image', sa.String(length=200), nullable=True),
    sa.Column('algorithm_used', sa.Text(), nullable=False),
    sa.Column('best_algorithm', sa.String(length=100), nullable=True),
    sa.Column('model_type', sa.Text(), nullable=False),
    sa.Column('source_link', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cnn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('objectives', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('source_link', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('datatype', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cnn')
    op.drop_table('ann')
    # ### end Alembic commands ###
